### ISSUE TITLE
A way to not parse an array of 1?

### ISSUE THREAD

**Issue by Nic128** [peterKaleta/fixture-factory#14]
This code results in the array `roles` being parsed and return an object only.

```
fixtureFactory.register('user', {
    type: 'admin',
    firstName: 'Daniel',
    roles: [{
        id: 'random.uuid',
        name: 'internet.userName'
    }, 1]
  });
fixtureFactory.generateOne('user');
```

In most cases, it's fine. Is there a way to keep the array with that one object, to not have it parsed?

**Comment by lunelson** [comment]
👍 
This code should result in `roles` being an array with one object in it, but it collapses to being just an object

**Comment by Shinypaper** [comment]
Is this or any issue being looked still being looked at?

**Comment by lunelson** [comment]
(please close)
