### ISSUE TITLE
Don't pass empty options object

### ISSUE THREAD

**Issue by jbrumwell** [peterKaleta/fixture-factory#6]
Currently the following code is broken;

``` js
fixtureFactory.generateOne({
  email: 'internet.email'
});
```

Since we are passing an empty object https://github.com/colonyamerican/fixture-factory/blob/master/index.js#L43 it prefixes the email with objectObject.  Do some methods break if we don't pass an object as a param?

**Comment by peterKaleta** [comment]
fixed with new version of faker and rewrite to es7.
